/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./ipem_webapp/templates/**/*.{html,js}",
        "./ipem_webapp/templates/**/**/*.{html,js}",
        "./ipem_webapp/templates/*.{html,js}",
        "./ipem_webapp/**/*.py",
    ],
    safelist: [
        'row-span-1',
        'row-span-2',
        'row-span-3',
        'row-span-4',
        'row-span-5',
        'row-span-6',
        'row-span-7',
        'row-span-8',
        'row-span-9',
        'row-span-10',
        'row-span-11',
        'row-span-12',
        'row-span-13',
        'row-span-14',
        'row-span-15',
        'row-span-16',
        'row-span-17',
        'row-span-18',
        'row-span-19',
        'row-span-20',
        'col-span-1',
        'col-span-2',
        'col-span-3',
        'col-span-4',
        'col-span-5',
        'col-span-6',
        'col-span-7',
        'col-span-8',
        'col-span-9',
        'col-span-10',
        'col-span-11',
        'col-span-12',
        'col-span-13',
        'col-span-14',
        'col-span-15',
        'col-span-16',
        'col-span-17',
        'col-span-18',
        'col-span-19',
        'col-span-20',
        'col-start-3',
        'col-start-4',
    ],
    theme: {
    extend: {
        gridTemplateColumns: {
            '16': 'repeat(16, minmax(0, 1fr))',
            '17': 'repeat(17, minmax(0, 1fr))',
            '18': 'repeat(18, minmax(0, 1fr))',
            '19': 'repeat(19, minmax(0, 1fr))',
            '20': 'repeat(20, minmax(0, 1fr))',
            '21': 'repeat(21, minmax(0, 1fr))',
            '22': 'repeat(22, minmax(0, 1fr))',
            '23': 'repeat(23, minmax(0, 1fr))',
        },
        gridColumn: {
            'span-1': 'span 1 / span 1',
            'span-2': 'span 2 / span 2',
            'span-3': 'span 3 / span 3',
            'span-4': 'span 4 / span 4',
            'span-5': 'span 5 / span 5',
            'span-6': 'span 6 / span 6',
            'span-7': 'span 7 / span 7',
            'span-8': 'span 8 / span 8',
            'span-9': 'span 9 / span 9',
            'span-10': 'span 10 / span 10',
            'span-11': 'span 11 / span 11',
            'span-12': 'span 12 / span 12',
            'span-13': 'span 13 / span 13',
            'span-14': 'span 14 / span 14',
            'span-15': 'span 15 / span 15',
            'span-16': 'span 16 / span 16',
            'span-17': 'span 17 / span 17',
            'span-18': 'span 18 / span 18',
            'span-19': 'span 19 / span 19',
            'span-20': 'span 20 / span 20',
        },
        gridRow: {
            'span-1': 'span 1 / span 1',
            'span-2': 'span 2 / span 2',
            'span-3': 'span 3 / span 3',
            'span-4': 'span 4 / span 4',
            'span-5': 'span 5 / span 5',
            'span-6': 'span 6 / span 6',
            'span-7': 'span 7 / span 7',
            'span-8': 'span 8 / span 8',
            'span-9': 'span 9 / span 9',
            'span-10': 'span 10 / span 10',
            'span-11': 'span 11 / span 11',
            'span-12': 'span 12 / span 12',
            'span-13': 'span 13 / span 13',
            'span-14': 'span 14 / span 14',
            'span-15': 'span 15 / span 15',
            'span-16': 'span 16 / span 16',
            'span-17': 'span 17 / span 17',
            'span-18': 'span 18 / span 18',
            'span-19': 'span 19 / span 19',
            'span-20': 'span 20 / span 20',
        }
    },
    },
    plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    ],
}
