# Generated by Django 4.0.10 on 2023-04-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSolvingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Situation Analysis'), ('P', 'Problem Containment'), ('A', 'Detection of Alternative Solutions'), ('L', 'Selection of Solutions'), ('T', 'Analysis of Consequences'), ('E', 'Deciding and Implementing'), ('N', 'Recapitulation and Learning')], default='S', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='models.problemsolvingactivity')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRODUCT', 'Product'), ('VALIDATION', 'Validation System'), ('PRODUCTION', 'Production System'), ('STRATEGY', 'Strategy')], default='PRODUCT', max_length=10)),
                ('generation', models.IntegerField(choices=[(0, 'Current'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], default=0)),
                ('generation_type', models.CharField(choices=[('CURRENT', 'Current'), ('PREVIOUS', 'Previous'), ('FOLLOWING', 'Following')], default='CURRENT', max_length=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer', to='models.model')),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('a', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a', to='models.problemsolvingactivity')),
                ('e', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e', to='models.problemsolvingactivity')),
                ('l', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l', to='models.problemsolvingactivity')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_activity', to='models.layer')),
                ('n', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n', to='models.problemsolvingactivity')),
                ('p', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to='models.problemsolvingactivity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='models.developmentactivity')),
                ('s', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s', to='models.problemsolvingactivity')),
                ('t', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t', to='models.problemsolvingactivity')),
            ],
        ),
    ]
