# Generated by Django 4.0.10 on 2023-04-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='generation',
        ),
    ]
