# Generated by Django 4.1.7 on 2023-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0003_remove_layer_generation_type_layer_generation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="generation",
            field=models.CharField(
                choices=[
                    ("CURRENT", "n"),
                    ("PREVIOUS_1", "n-1"),
                    ("PREVIOUS_2", "n-2"),
                    ("PREVIOUS_3", "n-3"),
                    ("FOLLOWING_1", "n+1"),
                    ("FOLLOWING_2", "n+2"),
                    ("FOLLOWING_3", "n+3"),
                ],
                default="CURRENT",
                max_length=11,
            ),
        ),
    ]
