# Generated by Django 4.1.7 on 2023-04-30 14:24

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0004_alter_layer_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="stream",
            field=streamfield.fields.StreamField(
                blank=True, default=list, verbose_name="Page blocks"
            ),
        ),
    ]
