# Generated by Django 4.1.7 on 2023-05-01 14:43

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0006_remove_problemsolvingactivity_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentactivity",
            name="stream",
            field=streamfield.fields.StreamField(
                blank=True, default=list, verbose_name="Page blocks"
            ),
        ),
    ]
