# Generated by Django 4.1.7 on 2023-05-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0007_developmentactivity_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentactivity",
            name="description",
            field=models.TextField(default="This is a description"),
            preserve_default=False,
        ),
    ]
