# Generated by Django 4.1.7 on 2023-05-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0009_model_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentactivity",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
