# Generated by Django 4.0.10 on 2023-03-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
