# Generated by Django 4.0.10 on 2023-04-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0004_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
