# Generated by Django 4.1.7 on 2023-04-30 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("methods", "0005_delete_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="method",
            name="s_rating",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
    ]
