# Generated by Django 4.1.7 on 2023-05-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0007_developmentactivity_stream"),
        ("methods", "0007_method_a_rating_method_e_rating_method_l_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="method",
            name="activity",
            field=models.ManyToManyField(
                related_name="method",
                through="methods.MethodRegistry",
                to="models.developmentactivity",
            ),
        ),
    ]
